name: pocketbase_drift
description: A pocketbase client backed by drift database.\
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: 1.3.0
  pocketbase: 0.22.0
  drift: 2.26.0
  sqlite3_flutter_libs: 0.5.31
  path_provider: 2.1.5
  path: 1.9.0
  sqlite3: ^2.0.0
  drift_dev: 2.26.0
  shortid: ^0.1.2
  shared_preferences: 2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  build_runner: 2.4.15

flutter:

flutter_scripts:
  schema: flutter pub run drift_dev schema dump lib/src/database/database.dart drift_schemas/